title: "The Feedback"
email: ian@thethingthatiwant.com
timezone: UTC
baseurl: "/tttiw-typeform"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Ian
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# ganalytics: UA-113961478-1

# Authors
authors:
  morna:
    name: 'Morna Simpson'
    display_name: Morna
    avatar: 'assets/images/morna.jpg'
    email: morna.simpson@gmail.com
    web: https://facebook.com/girlgeekscotland
    twitter: https://twitter.com/girlgeeks
    linkedin: https://linkedin.com/in/mornasimpson
    description: "Truth Seeker, open to contract roles in User Research, Service Design & Business Analysis, focused on Discovery research, with a special interest in digital behaviour change technology."
  john:
    name: 'Ifraz Mughal'
    display_name: Ifraz
    avatar: 'assets/images/ifraz.jpg'
    email:  ifrazm@googlemail.com
    web: https://ifrazmughal.com
    twitter: https://twitter.com/ifraz
    linkedin: https://linkedin.com/in/ifraz
    description: "Senior UX researcher with 15+ years of experience in User Centred Design, I thrive on embedding research into the cadence of digital delivery projects."

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives